package com.pudge.entity.bike;

import java.io.Serializable;
import java.util.Date;

public class BikeAreaLog implements Serializable{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bike_area_log.bike_area_log_id
	 * @mbggenerated  Sun Apr 19 18:04:28 CST 2015
	 */
	private String bikeAreaLogId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bike_area_log.bike_area_nos
	 * @mbggenerated  Sun Apr 19 18:04:28 CST 2015
	 */
	private String bikeAreaNos;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bike_area_log.bike_area_names
	 * @mbggenerated  Sun Apr 19 18:04:28 CST 2015
	 */
	private String bikeAreaNames;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bike_area_log.area_rent_nums
	 * @mbggenerated  Sun Apr 19 18:04:28 CST 2015
	 */
	private Integer areaRentNums;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bike_area_log.area_return_nums
	 * @mbggenerated  Sun Apr 19 18:04:28 CST 2015
	 */
	private Integer areaReturnNums;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column bike_area_log.create_time
	 * @mbggenerated  Sun Apr 19 18:04:28 CST 2015
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bike_area_log.bike_area_log_id
	 * @return  the value of bike_area_log.bike_area_log_id
	 * @mbggenerated  Sun Apr 19 18:04:28 CST 2015
	 */
	public String getBikeAreaLogId() {
		return bikeAreaLogId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bike_area_log.bike_area_log_id
	 * @param bikeAreaLogId  the value for bike_area_log.bike_area_log_id
	 * @mbggenerated  Sun Apr 19 18:04:28 CST 2015
	 */
	public void setBikeAreaLogId(String bikeAreaLogId) {
		this.bikeAreaLogId = bikeAreaLogId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bike_area_log.bike_area_nos
	 * @return  the value of bike_area_log.bike_area_nos
	 * @mbggenerated  Sun Apr 19 18:04:28 CST 2015
	 */
	public String getBikeAreaNos() {
		return bikeAreaNos;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bike_area_log.bike_area_nos
	 * @param bikeAreaNos  the value for bike_area_log.bike_area_nos
	 * @mbggenerated  Sun Apr 19 18:04:28 CST 2015
	 */
	public void setBikeAreaNos(String bikeAreaNos) {
		this.bikeAreaNos = bikeAreaNos;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bike_area_log.bike_area_names
	 * @return  the value of bike_area_log.bike_area_names
	 * @mbggenerated  Sun Apr 19 18:04:28 CST 2015
	 */
	public String getBikeAreaNames() {
		return bikeAreaNames;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bike_area_log.bike_area_names
	 * @param bikeAreaNames  the value for bike_area_log.bike_area_names
	 * @mbggenerated  Sun Apr 19 18:04:28 CST 2015
	 */
	public void setBikeAreaNames(String bikeAreaNames) {
		this.bikeAreaNames = bikeAreaNames;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bike_area_log.area_rent_nums
	 * @return  the value of bike_area_log.area_rent_nums
	 * @mbggenerated  Sun Apr 19 18:04:28 CST 2015
	 */
	public Integer getAreaRentNums() {
		return areaRentNums;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bike_area_log.area_rent_nums
	 * @param areaRentNums  the value for bike_area_log.area_rent_nums
	 * @mbggenerated  Sun Apr 19 18:04:28 CST 2015
	 */
	public void setAreaRentNums(Integer areaRentNums) {
		this.areaRentNums = areaRentNums;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bike_area_log.area_return_nums
	 * @return  the value of bike_area_log.area_return_nums
	 * @mbggenerated  Sun Apr 19 18:04:28 CST 2015
	 */
	public Integer getAreaReturnNums() {
		return areaReturnNums;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bike_area_log.area_return_nums
	 * @param areaReturnNums  the value for bike_area_log.area_return_nums
	 * @mbggenerated  Sun Apr 19 18:04:28 CST 2015
	 */
	public void setAreaReturnNums(Integer areaReturnNums) {
		this.areaReturnNums = areaReturnNums;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column bike_area_log.create_time
	 * @return  the value of bike_area_log.create_time
	 * @mbggenerated  Sun Apr 19 18:04:28 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column bike_area_log.create_time
	 * @param createTime  the value for bike_area_log.create_time
	 * @mbggenerated  Sun Apr 19 18:04:28 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}